services:
  - type: web
    name: gema-app
    runtime: node
    plan: starter
    region: oregon
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd .next/standalone && NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        value: https://gema-l9le.onrender.com
    healthCheckPath: /
    autoDeploy: true
